# checkout-setup.yml

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup toolchain cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-toolchain-${{ hashFiles('**/*.txt') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
