# compile-sketches.yml

on:
  workflow_call:

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: esp32:esp32:esp32
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile all test sketches
        uses: arduino/compile-sketches@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          sketch-paths: |
            test
            release
          libraries: |
            - name: AUnit
              version: 1.7.1
          sketches-report-path: sketches-reports
          enable-deltas-report: false
          enable-warnings-report: true

      - name: Upload compile report
        uses: actions/upload-artifact@v4
        with:
          name: test-compile-report
          path: sketches-reports
