# format-check.yml

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check code formatting
        run: |
          find . -name "*.cpp" -o -name "*.h" -o -name "*.ino" | xargs clang-format --dry-run --Werror
