name: Bump Version

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  bump:
    name: Bump version & open PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Read current version
        id: read_ver
        run: |
          echo "ver=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: bump
        run: |
          IFS='.' read -r MAJ MIN <<< "${{ steps.read_ver.outputs.ver }}"
          MIN=$((MIN + 1))
          NEW="${MAJ}.${MIN}"
          echo "$NEW" > version.txt
          echo "newver=$NEW" >> $GITHUB_OUTPUT

      - name: Update code version
        run: |
          sed -i -E \
            "s|(const double current_version *= *)[0-9]+\.[0-9]+(;)|\1${{ steps.bump.outputs.newver }}\2|" \
            release/release.ino

      - name: Configure Git user
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create bump branch & commit
        id: commit
        run: |
            BRANCH="bump/v${{ steps.bump.outputs.newver }}-${{ github.run_id }}"
            git checkout -b $BRANCH
            git add version.txt release/release.ino
            git commit -m "chore: bump version to v${{ steps.bump.outputs.newver }}"
            git push --force-with-lease origin "$BRANCH"
            echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "chore: bump version to v${{ steps.bump.outputs.newver }}"
            branch: ${{ steps.commit.outputs.branch }}
            title: "Bump version to v${{ steps.bump.outputs.newver }}"
            body: "自動バージョンアップ PR: v${{ steps.bump.outputs.newver }}"
            base: main