name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  checkout-setup:
    uses: ./.github/workflows/wf-checkout-setup.yml

  format:
    needs: checkout-setup
    uses: ./.github/workflows/wf-format-check.yml

  lint:
    needs: format
    uses: ./.github/workflows/wf-lint.yml

  coverage:
    needs: lint
    uses: ./.github/workflows/wf-coverage-report.yml

  unit-test:
    needs: coverage
    uses: ./.github/workflows/wf-unit-test.yml

  build:
    needs: unit-test
    uses: ./.github/workflows/wf-compile-sketches.yml