name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  checkout-setup:
    uses: ./.github/workflows/jobs/checkout-setup.yml

  format:
    needs: checkout-setup
    uses: ./.github/workflows/jobs/format-check.yml

  lint:
    needs: format
    uses: ./.github/workflows/jobs/lint.yml

  coverage:
    needs: lint
    uses: ./.github/workflows/jobs/coverage-report.yml

  unit-test:
    needs: coverage
    uses: ./.github/workflows/jobs/unit-test.yml

  build:
    needs: unit-test
    uses: ./.github/workflows/jobs/compile-sketches.yml