# .github/workflows/release.yml
name: Release Automation

on:
  pull_request:
    # PRが閉じたタイミングで実行
    types:
      - closed
    # mainブランチのみを対象とする
    branches:
      - main

permissions:
  contents: read

env:
  SKETCH_DIR: release

jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # リリースノートを書くためwrite用のpermissionを付与
      pull-requests: write
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@v4

      # 前回のリリースタグを取得する
      - name: Get previous tag
        id: pre_tag
        run: |
          echo "pre_tag=$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)" >> $GITHUB_OUTPUT

      # タグを生成する。バージョンファイルの内容をもとに、生成する。例： v4.10
      - name: Generate tag
        id: release_tag
        run: |
          release_version=$(cat version.txt | tr -d '\n')
          echo "release_tag=$release_version" >> $GITHUB_OUTPUT

      # PRのDescriptionを取得しマークダウン形式に変換する
      - name: Get pr description
        id: pr_description
        run: |
          echo "pr_description=$(curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number}}' \
            | jq .body | awk '{if ($0 == "null") print ""; else print}')" >> $GITHUB_OUTPUT

      # 前回リリースからの差分をもとに、変更点を取得する
      - name: Generate release note changes
        id: changes
        run: |
          echo "changes=$(
          curl -X POST \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
            -d '{
              "tag_name": "${{ steps.release_tag.outputs.release_tag }}",
              "previous_tag_name": "${{ steps.pre_tag.outputs.pre_tag }}",
              "target_commitish": "main"
            }' | jq .body
          )" >> $GITHUB_OUTPUT

      # リリースノートの本文を作成する
      - name: Create release note body
        id: release_note_body
        run: |
          echo "release_note_body=$(echo \
            ${{ steps.pr_description.outputs.pr_description }} \
            ${{ steps.changes.outputs.changes }} \
            | sed 's/\\"//g' | sed 's/["“]//g')" >> $GITHUB_OUTPUT

      # タグを切り、リリースノートを作成する
      - name: Create Release
        id: create_release
        run: |
          # 1) リリース作成 API を叩いて、ボディだけ response_body.txt に、ステータスコードだけ status_code に格納
          status_code=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{ \
              \"tag_name\": \"${{ steps.release_tag.outputs.release_tag }}\", \
              \"target_commitish\": \"main\", \
              \"name\": \"${{ steps.release_tag.outputs.release_tag }}\", \
              \"body\": \"${{ steps.release_note_body.outputs.release_note_body }}\" \
            }" \
            -w "%{http_code}" \
            -o response_body.txt \
            https://api.github.com/repos/${{ github.repository }}/releases)

          echo "Status Code: $status_code"
          if [ "$status_code" -ne 201 ]; then
            echo "Failed to create release:"
            cat response_body.txt
            exit 1
          fi

          # 2) ボディから upload_url と release_id を抽出
          # ── upload_url は "{?name,label}" がついてくるので末尾を取り除く
          upload_url=$(jq -r .upload_url response_body.txt \
            | sed -E 's/\{\?name,label\}$//')
          release_id=$(jq -r .id response_body.txt)

          echo "upload_url=$upload_url" >> $GITHUB_OUTPUT
          echo "release_id=$release_id" >> $GITHUB_OUTPUT

      # ── ここからバイナリ生成＋アセットアップロード ──

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: '1.2.2'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ESP32 platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Build release sketch
        run: |
          mkdir -p ${{ env.SKETCH_DIR }}/build
          arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --build-path ${{ env.SKETCH_DIR }}/build \
            ${{ env.SKETCH_DIR }}/release.ino

      - name: Rename release binary
        run: |
          mkdir -p release-${{ steps.release_tag.outputs.release_tag }}
          mv ${{ env.SKETCH_DIR }}/build/${{ env.SKETCH_DIR }}.ino.bin release-${{ steps.release_tag.outputs.release_tag }}/firmware.bin

      - name: Create ZIP archive
        run: |
          zip -r release-${{ steps.release_tag.outputs.release_tag }}.zip release-${{ steps.release_tag.outputs.release_tag }} version.txt

      - name: Upload Release Asset via gh
        env:
          RELEASE_ID: ${{ steps.create_release.outputs.release_id }}
          REPO: ${{ github.repository }}
          TAG: ${{ steps.release_tag.outputs.release_tag }}
        run: |
          ASSET="release-${TAG}.zip"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${REPO}/releases/${RELEASE_ID}/assets?name=${ASSET} \
            -F "data=@${ASSET};type=application/zip"