name: Release Pipeline
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'どちらをカウントアップするか'
        required: true
        type: choice
        options:
          - minor
          - major

jobs:
  bump:
    uses: ./.github/workflows/wf-version-bump.yml
    with:
      bump: ${{ github.event.inputs.bump }}

  build_release:
    needs: bump
    uses: ./.github/workflows/wf-build.yml
    with:
      version: ${{ needs.bump.outputs.new }}

  upload_assets:
    needs: build_release
    uses: ./.github/workflows/wf-artifact-upload.yml
    with:
      version: ${{ needs.bump.outputs.new }}

  notify:
    needs: upload_assets
    uses: ./.github/workflows/wf-notify.yml
    with:
      version: ${{ needs.bump.outputs.new }}