name: Release Pipeline

# ワークフロー全体に付与する権限を指定
permissions:
  contents: write        # リリースアーティファクトのアップロード等で必要
  issues: read           # プルリクエスト作成時の情報取得など
  pull-requests: write   # リリースPR作成

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'どちらをカウントアップするか'
        required: true
        type: choice
        options:
          - minor
          - major

jobs:
  bump:
    uses: ./.github/workflows/wf-version-bump.yml
    with:
      bump: ${{ github.event.inputs.bump }}

  build_release:
    needs: bump
    uses: ./.github/workflows/wf-build.yml
    with:
      version: ${{ needs.bump.outputs.new }}

  upload_assets:
    needs: build_release
    uses: ./.github/workflows/wf-artifact-upload.yml
    with:
      version: ${{ needs.bump.outputs.new }}

  notify:
    needs: upload_assets
    uses: ./.github/workflows/wf-notify.yml
    with:
      version: ${{ needs.bump.outputs.new }}