name: Test Sketches

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 環境をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. cpplint をインストール
      - name: Install cpplint
        run: |
          python -m pip install --upgrade pip
          pip install cpplint

      # 4. Arduino スケッチ (*.ino) を含む C/C++ ファイルを対象に lint を実行
      #    "copyright" ルールを除外するため --filter=-legal/copyright を追加
      - name: Run cpplint
        run: |
          echo "Checking C/C++/Arduino files with cpplint (excluding copyright)..."
          ERR=0
          for file in $(find . -type f \( -name '*.ino' -o -name '*.cpp' -o -name '*.h' \)); do
            echo "Linting $file"
            cpplint --filter=-legal/copyright --extensions=h,cpp,ino "$file" || ERR=1
          done
          if [ $ERR -ne 0 ]; then
            echo "::error ::cpplint found style violations. Please fix them."
            exit 1
          fi