name: Test Sketches

on:
  push: {}
  pull_request: {}

  workflow_dispatch:

jobs:
  test:
    name: 'test: ${{matrix.board.name}}'
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          board:
            - fqbn: esp32:esp32:esp32dev
              platforms: |
                - name: esp32:esp32
                  source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile all test sketches
        uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          sketch-paths: |
            tests/**/*.ino
          sketches-report-path: "sketches-reports"
          enable-deltas-report: true
          enable-warnings-report: true

      - name: Upload compile report
        uses: actions/upload-artifact@v3
        with:
          name: test-compile-report
          path: sketches-reports