name: Test Sketches

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 環境をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. cpplint をインストール
      - name: Install cpplint
        run: |
          python -m pip install --upgrade pip
          pip install cpplint

      # 4. Reviewdog をインストール
      - name: Install reviewdog
        run: |
          curl -sSL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
            | sh -s -- -b $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      # 5. cpplint を実行して Reviewdog で結果を PR にコメント
      - name: Run cpplint and report via Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find . -type f \( -name '*.ino' -o -name '*.cpp' -o -name '*.h' \) \
            | xargs cpplint --filter=-legal/copyright --extensions=h,cpp,ino 2>&1 \
            | reviewdog \
                -efm="%f:%l: %m" \
                -name="arduino-cpplint" \
                -reporter=github-pr-review \
                -fail-on-error=true