# .github/workflows/version-bump.yml
name: Version Bump

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Which part to bump: "minor" or "major"'
        required: true
        type: choice
        options:
          - minor
          - major

jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest
    permissions:
      contents: write    # for pushing tags & branches
      pull-requests: write
    outputs:
      new-version: ${{ steps.bump.outputs.new }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Read latest tag
        id: get-tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "latest=$TAG" >> $GITHUB_OUTPUT

      - name: Calculate new version
        id: calculate-new
        run: |
          LATEST=${{ steps.get-tag.outputs.latest }}
          BASE=${LATEST#v}
          IFS='.' read MAJOR MINOR <<< "$BASE"

          if [ "${{ inputs.bump }}" = "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
          else
            MINOR=$((MINOR + 1))
          fi

          NEW="v${MAJOR}.${MINOR}"
          echo "Calculated new version: $NEW"
          echo "new=$NEW" >> $GITHUB_OUTPUT

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version files
        id: bump-files
        run: |
          # version.txt
          echo "${{ steps.calculate-new.outputs.new }}" > version.txt
          # release/release.ino の定義を書き換え
          sed -i -E \
            "s|(const double current_version *= *)[0-9]+\.[0-9]+(;)|\1${{ steps.calculate-new.outputs.new }}\2|" \
            release/release.ino

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "chore: bump version to ${{ steps.calculate-new.outputs.new }}"
          title: "Release ${{ steps.calculate-new.outputs.new }}"
          body: |
            This PR prepares release ${{ steps.calculate-new.outputs.new }}.
          branch: "release/${{ steps.calculate-new.outputs.new }}"
          base: main
          add-paths: |
            version.txt
            release/release.ino