# notify.yml
# まだ実装方法が未定のため何もしないジョブとして定義します。

name: notify

on:
  workflow_call: {}

jobs:
  notify:
    name: notify (No-Op)
    runs-on: ubuntu-latest
    steps:
      - name: No action
        run: echo "Notify not yet implemented"
