# push-tag.yml

on:
  workflow_call:
    inputs:
      new_version:
        required: true
        type: string

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ inputs.new_version }}
          git push origin v${{ inputs.new_version }}
