on:
  workflow_call:
    inputs:
      bump:
        description: 'どちらのバージョンを上げるか ("major" or "minor")'
        required: true
        type: string

jobs:
  version-bump:
    runs-on: ubuntu-latest
    outputs:
      new: ${{ steps.bump.outputs.new }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Read latest tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "latest=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version.txt and release.ino
        id: bump
        run: |
          LATEST=${{ steps.tag.outputs.latest }}
          IFS='.' read MAJOR MINOR <<< "${LATEST#v}"
          if [[ "${{ inputs.bump }}" == "major" ]]; then
            MAJOR=$((MAJOR+1))
            MINOR=0
          else
            MINOR=$((MINOR+1))
          fi
          NEW="v${MAJOR}.${MINOR}"
          echo "$NEW" > version.txt
          sed -i -E "s/#define VERSION \".*\"/#define VERSION \"${NEW#v}\"/" release/release.ino
          echo "new=$NEW" >> $GITHUB_OUTPUT

      - name: Commit & push bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump version to ${{ steps.bump.outputs.new }}"
          file_pattern: |
            version.txt
            release/release.ino

      - name: Create release branch
        run: |
          BR="release/${{ steps.bump.outputs.new }}"
          git checkout -b "$BR"
          git push origin "$BR"
        shell: bash